# Generated by Django 5.2.5 on 2025-10-09 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picturest_app', '0004_bookmarkimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkimages',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to='picturest_app.userpictures'),
        ),
    ]
